package com.example.clearer.models

import android.media.Image
import java.time.LocalDateTime

//Problem class to construct all the questions generated by the user or pre-existing.
class Problem(
    var image: Image?,
    var problemString: String = "",
    var userAdjectivesList: MutableList<String> = mutableListOf(),
    var userNounsList: MutableList<String> = mutableListOf(),
    var userPronounsList: MutableList<String> = mutableListOf(),
    var userVerbsList: MutableList<String> = mutableListOf(),
    var apiAdjectivesList: MutableList<String>? = mutableListOf(),
    var apiNounsList: MutableList<String>? = mutableListOf(),
    var apiPronounsList: MutableList<String>? = mutableListOf(),
    var apiVerbsList: MutableList<String>? = mutableListOf(),
    var difficulty: String = "Medium",
    var date: String = ""
) {
}